credentials:
  usernames:
    admin:
      email: admin@tcm.com
      name: 管理员
      password: $2a$12$ltI5Oy0OjwGciiCsxf6.geXwCygMloiVDQBX.QzrSmfL/kBcQF.Du

cookie:
  expiry_days: 30
  key: tcm_system_secret_key
  name: tcm_session

preauthorized:
  emails:
    - admin@tcm.com
